# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f84a39abb49e6d5480729733034976643a927c9d0d5517ed61f07da49accadfe5bb31ab2f80531b38e2ee7be53e18822ca7725c0b6fc64f2ff1ecf773e17260

test:
  secret_key_base: 70b73c5dd7c5b40f3ab15b98f3e41c0aee1a6688b427dfb51970f9d95e59ca0445fc7a7f240dc15de6fded19e4554999e223f19828437773c4a19479fdabd728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
